services:

  push-posgtresv2:
    build: .
    container_name: push-posgtresv2
    ports:
      - "3015:3000"
    environment:
      PG_HOST: ${POSTGRES_HOST}
      PG_USER: ${POSTGRES_USER}
      PG_PASS: ${POSTGRES_PASSWORD}
      PG_DB: ${POSTGRES_DATABASE}
    networks:
      - database
      - node-exporter
      - reactive-resume-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  database:
    external: true
  node-exporter:
    external: true
  reactive-resume-network:
    external: true
